### ISSUE TITLE
When the application is started it fails to compile

### ISSUE THREAD

**Issue by emil-simeonov-se** [JosephReyes/accounts-app#1]
### Impact
This issue blocks me from finalising my review at the stage of verifying the UAT coverage.

### Scenario
1. Cloned this repo.
2. Ran `npm i`.
3. Ran `npm start`.
4. Open `http://localhost:3000/` in the Chromium web browser.

### Expected result
The `account-app` renders in a web browser.

### Actual result
I am presented with an empty screen with an error message that goes like this.
> Failed to compile
./node_modules/@apollo/client/core/LocalState.js
Module not found: Can't resolve 'graphql' in '/Users/user/dev/tmp/accounts-app/node_modules/@apollo/client/core'
This error occurred during the build time and cannot be dismissed.

**Comment by JosephReyes** [comment]
Hi Emil,

I just tried cloning this repo from scratch and it seems to work ok for me. Could I get you to try a few steps to hopefully fix this issue? If none of these work I can send you the zip with node_modules in it so you don't have to rely on an `npm i` step

1. Delete node_modules and all contents in its folder
2. Delete `package-lock.json`
3. Make sure you are using the public npm just to be sure by running `npm config set registry https://registry.npmjs.org`
4. Run `npm i`
5. Run `npm start`

Please do get in touch if these steps don't work

**Comment by emil-simeonov-se** [comment]
Just went trough the steps above. Still the same compilation error. Is there anything else I can do to run the app?

**Comment by JosephReyes** [comment]
Could you please send me your email? I'll try and send over a zip instead. Could you also get me your versions of npm and node please?

To get these run:
`npm -v`
`node -v`

**Comment by emil-simeonov-se** [comment]
Just for the record, the app compiles and starts normally once I updated npm 6 to npm 7. From my perspective this issue is solved. Thank you for getting to the bottom of it, @JosephReyes !
